description: ["Welcome to my github.io page! Updated: 02 Mar 2025"]
logo: files/github_prof_pic.jpg
remote_theme: BDHU/minimalist
color-scheme: light
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
